### ISSUE TITLE
'make -f Makefile.isbi train' fails with Theano and TensorFlow backends

### ISSUE THREAD

**Issue by stevendbrown** [mjpekala/bio-segmentation#1]
after changing `make.inc` to include `GPU=0` instead of `GPU=2`, running `make -f Makefile.isbi train` with Keras configured for the TensorFlow backend produces this error:

```
Traceback (most recent call last):
  File "./src/train.py", line 459, in <module>
    model = train_model(Xtrain, Ytrain, Xvalid, Yvalid, log=logger, **cmdLineArgs)
  File "./src/train.py", line 315, in train_model
    model = getattr(emm, modelName)() 
  File "/home/sdbrown/bio-segmentation/src/models.py", line 33, in ciresan_n3
    model.add(Convolution2D(48, 5, 5, border_mode='valid', input_shape=(1, n, n)))
  File "/usr/local/lib/python2.7/dist-packages/keras/models.py", line 276, in add
    layer.create_input_layer(batch_input_shape, input_dtype)
  File "/usr/local/lib/python2.7/dist-packages/keras/engine/topology.py", line 370, in create_input_layer
    self(x)
  File "/usr/local/lib/python2.7/dist-packages/keras/engine/topology.py", line 514, in __call__
    self.add_inbound_node(inbound_layers, node_indices, tensor_indices)
  File "/usr/local/lib/python2.7/dist-packages/keras/engine/topology.py", line 572, in add_inbound_node
    Node.create_node(self, inbound_layers, node_indices, tensor_indices)
  File "/usr/local/lib/python2.7/dist-packages/keras/engine/topology.py", line 149, in create_node
    output_tensors = to_list(outbound_layer.call(input_tensors[0], mask=input_masks[0]))
  File "/usr/local/lib/python2.7/dist-packages/keras/layers/convolutional.py", line 466, in call
    filter_shape=self.W_shape)
  File "/usr/local/lib/python2.7/dist-packages/keras/backend/tensorflow_backend.py", line 1579, in conv2d
    x = tf.nn.conv2d(x, kernel, strides, padding=padding)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/ops/gen_nn_ops.py", line 394, in conv2d
    data_format=data_format, name=name)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/framework/op_def_library.py", line 703, in apply_op
    op_def=op_def)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/framework/ops.py", line 2319, in create_op
    set_shapes_for_outputs(ret)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/framework/ops.py", line 1711, in set_shapes_for_outputs
    shapes = shape_func(op)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/framework/common_shapes.py", line 246, in conv2d_shape
    padding)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/framework/common_shapes.py", line 184, in get2d_conv_output_size
    (row_stride, col_stride), padding_type)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/framework/common_shapes.py", line 149, in get_conv_output_size
    "Filter: %r Input: %r" % (filter_size, input_size))
ValueError: Filter must not be larger than the input: Filter: (5, 5) Input: (1, 65)
Makefile.isbi:40: recipe for target 'train' failed
make: *** [train] Error 1
```

running the same command with Theano produces the following error:

```
Traceback (most recent call last):
  File "./src/train.py", line 459, in <module>
    model = train_model(Xtrain, Ytrain, Xvalid, Yvalid, log=logger, **cmdLineArgs)
  File "./src/train.py", line 315, in train_model
    model = getattr(emm, modelName)() 
  File "/home/sdbrown/bio-segmentation/src/models.py", line 50, in ciresan_n3
    model.add(Dense(200))
  File "/usr/local/lib/python2.7/dist-packages/keras/models.py", line 308, in add
    output_tensor = layer(self.outputs[0])
  File "/usr/local/lib/python2.7/dist-packages/keras/engine/topology.py", line 487, in __call__
    self.build(input_shapes[0])
  File "/usr/local/lib/python2.7/dist-packages/keras/layers/core.py", line 695, in build
    name='{}_W'.format(self.name))
  File "/usr/local/lib/python2.7/dist-packages/keras/initializations.py", line 59, in glorot_uniform
    return uniform(shape, s, name=name)
  File "/usr/local/lib/python2.7/dist-packages/keras/initializations.py", line 32, in uniform
    return K.random_uniform_variable(shape, -scale, scale, name=name)
  File "/usr/local/lib/python2.7/dist-packages/keras/backend/theano_backend.py", line 140, in random_uniform_variable
    return variable(np.random.uniform(low=low, high=high, size=shape),
  File "mtrand.pyx", line 1565, in mtrand.RandomState.uniform (numpy/random/mtrand/mtrand.c:17311)
OverflowError: Range exceeds valid bounds
Makefile.isbi:40: recipe for target 'train' failed
make: *** [train] Error 1
```

testing Keras using [this script](https://github.com/fchollet/keras/raw/master/examples/mnist_mlp.py) results on only the expected output and apparently successful training (final test accuracy 0.9819). testing TensorFlow with `python -m tensorflow.models.image.mnist.convolutional` works similarly well, and testing Theano with `python -c 'import theano; theano.test()` also seems to pass.

**Comment by mjpekala** [comment]
Hi Steven,
Thanks for letting me know about this.  It has been awhile since I've run this code and the Keras APIs have undergone some changes in the meantime.  I made a few small changes on the  "keras-update" branch to fix issues I was seeing with Keras 1.0.7 (Theano backend) on my end.  However, I think what you are seeing may be something different.  Can you let me know what version of Keras you are using?

**Comment by stevendbrown** [comment]
i'm using keras version 1.1.0.

**Comment by mjpekala** [comment]
Ok, I put a few more changes on the "keras-update" branch to accomodate keras 1.1.0.  I still didn't see exactly the issue you reported but you might give this branch a try just to see what happens. 

To simplify matters you might want to verify the following works (from the `src` directory):

```
-bash-4.1$ THEANO_FLAGS='device=gpu0' ipython
Python 2.7.11 |Anaconda 2.5.0 (64-bit)| (default, Dec  6 2015, 18:08:32) 

In [1]: import models
Using Theano backend.
Using gpu device 0: GeForce GTX TITAN (CNMeM is disabled, cuDNN not available)

In [2]: n3 = models.ciresan_n3()

In [3]: n3.input_shape
Out[3]: (None, 1, 65, 65)

In [4]: n3.output_shape
Out[4]: (None, 2)
```

**Comment by mjpekala** [comment]
I happened to be running on a different system today and have observed the issue you originally reported.  At some point I must have set "image_dim_ordering" to "th" in my `~/.keras/keras.json` (or maybe this was the default at some point?).  Anyway, the code assumes the default ordering is  "th" and if the default is "tf" [as is evidently the case now](https://keras.io/layers/convolutional/) there will be problems.  You can either change your keras.json (example below) 

```
{
    "image_dim_ordering": "th",
    "epsilon": 1e-07,
    "floatx": "float32",
    "backend": "theano"
}
```

or use the latest update to the "keras-update" branch which has been changed to no longer rely on the default value.  

As soon as I can verify everything works as before I'll merge this branch.  Thanks again for the report.

**Comment by stevendbrown** [comment]
thanks, that definitely gets further than it did before. i do get a new error, though:

```
sdbrown@agnesi:~/bio-segmentation$ make -f Makefile.isbi train
PYTHONPATH=./src:./src/thirdparty THEANO_FLAGS='floatX=float32,device=gpu0' python ./src/train.py \
        --x-train ./data/ISBI2012/train-volume.tif \
        --train-slices "range(0,27)" \
        --y-train ./data/ISBI2012/train-labels.tif \
        --x-valid ./data/ISBI2012/train-volume.tif \
        --y-valid ./data/ISBI2012/train-labels.tif \
        --valid-slices "[29,]"  \
        --out-dir ./Models/ISBI2012 \
        --num-epochs 30
Using Theano backend.
Couldn't import dot_parser, loading of dot files will not be possible.
Using gpu device 0: GeForce GTX 1070 (CNMeM is disabled, cuDNN 5105)
/home/sdbrown/.local/lib/python2.7/site-packages/theano/sandbox/cuda/__init__.py:600: UserWarning: Your cuDNN version is more recent than the one Theano officially supports. If you see any problems, try updating Theano or downgrading cuDNN to version 5.
  warnings.warn(warn)
[2016-10-12 08:28:26,740:train_model:INFO]  training volume dimensions:   (27, 1, 512, 512)
[2016-10-12 08:28:26,745:train_model:INFO]  training values min/max:      0, 1
[2016-10-12 08:28:26,984:train_model:INFO]  training class labels:        [ 0.  1.]
[2016-10-12 08:28:27,235:train_model:INFO]      class 0 has 1572782 instances
[2016-10-12 08:28:27,248:train_model:INFO]      class 1 has 5505106 instances
[2016-10-12 08:28:27,248:train_model:INFO]  
[2016-10-12 08:28:27,248:train_model:INFO]  validation volume dimensions: (1, 1, 512, 512)
[2016-10-12 08:28:27,248:train_model:INFO]  validation values min/max:    0, 1
[2016-10-12 08:28:27,254:train_model:INFO]  validation class labels:      [ 0.  1.]
[2016-10-12 08:28:27,255:train_model:INFO]  creating CNN
/usr/local/lib/python2.7/dist-packages/keras/models.py:540: UserWarning: "class_mode" argument is deprecated, please remove it.
  warnings.warn('"class_mode" argument is deprecated, '
[2016-10-12 08:28:27,698:train_model:INFO]  starting training epoch 0 (of 30)
/home/sdbrown/bio-segmentation/src/emlib.py:524: VisibleDeprecationWarning: using a non-integer number instead of an integer will result in an error in the future
  self._Yb[jj,yj] = 1
/usr/local/lib/python2.7/dist-packages/keras/models.py:702: UserWarning: The "accuracy" argument is deprecated, instead you should pass the "accuracy" metric to the model at compile time:
`model.compile(optimizer, loss, metrics=["accuracy"])`
  warnings.warn('The "accuracy" argument is deprecated, '
Traceback (most recent call last):
  File "./src/train.py", line 459, in <module>
    model = train_model(Xtrain, Ytrain, Xvalid, Yvalid, log=logger, **cmdLineArgs)
  File "./src/train.py", line 329, in train_model
    nBatches=maxMbPerEpoch)
  File "./src/train.py", line 152, in _train_one_epoch
    loss, acc = model.train_on_batch(Xi, Yi, accuracy=True)
TypeError: iteration over a 0-d array
Makefile.isbi:40: recipe for target 'train' failed
make: *** [train] Error 1
sdbrown@agnesi:~/bio-segmentation$ 
```

it seems like the training data is loading right (i.e. training volume dimensions (27, 1, 512, 512)) but maybe something isn't converting correctly somewhere. do i need to reformat the training data e.g. split it into separate TIFFs?

**Comment by mjpekala** [comment]
Are you using the keras-update branch?  The trace above looks like it may be coming from master.
